#
#  SPDX-License-Identifier: MIT
#
#  Author: Siddharth Chandrasekaran
#  Date: Mon Sep 16 00:25:31 IST 2019
#

dist: trusty
sudo: require

language: c
compiler: gcc

addons:
  apt:
    packages:
      - gcc-6
      - cmake3

script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - mkdir build && cd build
    - cmake ..
    - make
