#
#  Copyright (c) 2019 Siddharth Chandrasekaran <siddharth@embedjournal.com>
#
#  SPDX-License-Identifier: Apache-2.0
#

dist: bionic
sudo: require
os:
  - linux

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - cmake3

script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build && cd build
    - cmake ..
    - make
    - make check
