[package]
edition = "2021"
name = "osdp"
version = "0.1.0"
authors = ["Siddharth Chandrasekran <sidcha.dev@gmail.com>"]
description = "Library implementation of IEC 60839-11-5 OSDP (Open Supervised Device Protocol)"
documentation = "https://libosdp.sidcha.dev/rust"
homepage = "https://libosdp.sidcha.dev/"
readme = "README.md"
repository = "https://github.com/goToMain/libosdp"
license = "Apache-2.0"
keywords = ["osdp", "libosdp", "protocol", "sia", "osdpctl", "weigand" ]
categories = ["development-tools", "embedded"]

[build-dependencies]
anyhow = "1.0.75"
cc = "1.0.83"
bindgen = "0.68.1"

[dependencies]
anyhow = "1.0.75"
bitflags = "2.4.0"
