#
# Copyright (c) 2020-2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CmakeBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: make
      run: VERBOSE=1 make
    - name: pacakge
      run: |
        make package
        make package_source
        rm -rf ./packages/_CPack_Packages/
        rm -f ./packages/*.tar.bz2
    - uses: actions/upload-artifact@v2
      with:
        name: libosdp-ci-binaries.zip
        path: ./packages/

  MakeBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: |
        ./configure.sh
    - name: make
      run: make V=1

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: cmake .
    - name: pytest
      run: |
        python3 -m pip install -r tests/pytest/requirements.txt
        make check
    - name: unit-tests
      run: |
        make check-ut

  CheckPatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: ClangFormatCheck
      run: |
        ./scripts/clang-format-check.sh
