#
# Copyright (c) 2020 Siddharth Chandrasekaran <siddharth@embedjournal.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      SHORT_HASH: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: make
      run: make
    - name: pacakge
      run: |
        make package
        make package_source
        rm -rf ./packages/_CPack_Packages/
    - uses: actions/upload-artifact@v2
      with:
        name: libosdp-ci-binaries-${SHORT_HASH}.zip
        path: ./packages/

  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make check
      run: make check
