#
# Copyright (c) 2020-2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Publish Crate libosdp

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'Rust-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: Publish Crate - libosdp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: katyo/publish-crates@v2
      with:
        args: -p libosdp
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
